// Tamil is first — it's the inspiration ❤️
const LANGUAGES = [
  { code: 'ta', apiCode: 'ta',    name: 'Tamil',       native: 'தமிழ்',           dir: 'ltr', special: true },
  { code: 'es', apiCode: 'es',    name: 'Spanish',     native: 'Español',          dir: 'ltr' },
  { code: 'fr', apiCode: 'fr',    name: 'French',      native: 'Français',         dir: 'ltr' },
  { code: 'de', apiCode: 'de',    name: 'German',      native: 'Deutsch',          dir: 'ltr' },
  { code: 'ja', apiCode: 'ja',    name: 'Japanese',    native: '日本語',            dir: 'ltr' },
  { code: 'ko', apiCode: 'ko',    name: 'Korean',      native: '한국어',            dir: 'ltr' },
  { code: 'zh', apiCode: 'zh-CN', name: 'Chinese',     native: '中文',              dir: 'ltr' },
  { code: 'ar', apiCode: 'ar',    name: 'Arabic',      native: 'العربية',           dir: 'rtl' },
  { code: 'hi', apiCode: 'hi',    name: 'Hindi',       native: 'हिन्दी',            dir: 'ltr' },
  { code: 'mr', apiCode: 'mr',    name: 'Marathi',     native: 'मराठी',             dir: 'ltr' },
  { code: 'gu', apiCode: 'gu',    name: 'Gujarati',    native: 'ગુજરાતી',           dir: 'ltr' },
  { code: 'kn', apiCode: 'kn',    name: 'Kannada',     native: 'ಕನ್ನಡ',             dir: 'ltr' },
  { code: 'or', apiCode: 'or',    name: 'Odia',        native: 'ଓଡ଼ିଆ',             dir: 'ltr' },
  { code: 'pa', apiCode: 'pa',    name: 'Punjabi',     native: 'ਪੰਜਾਬੀ',            dir: 'ltr' },
  { code: 'pt', apiCode: 'pt',    name: 'Portuguese',  native: 'Português',        dir: 'ltr' },
  { code: 'ru', apiCode: 'ru',    name: 'Russian',     native: 'Русский',          dir: 'ltr' },
  { code: 'it', apiCode: 'it',    name: 'Italian',     native: 'Italiano',         dir: 'ltr' },
  { code: 'tr', apiCode: 'tr',    name: 'Turkish',     native: 'Türkçe',           dir: 'ltr' },
  { code: 'pl', apiCode: 'pl',    name: 'Polish',      native: 'Polski',           dir: 'ltr' },
  { code: 'nl', apiCode: 'nl',    name: 'Dutch',       native: 'Nederlands',       dir: 'ltr' },
  { code: 'sv', apiCode: 'sv',    name: 'Swedish',     native: 'Svenska',          dir: 'ltr' },
  { code: 'he', apiCode: 'he',    name: 'Hebrew',      native: 'עברית',            dir: 'rtl' },
  { code: 'fa', apiCode: 'fa',    name: 'Persian',     native: 'فارسی',            dir: 'rtl' },
  { code: 'el', apiCode: 'el',    name: 'Greek',       native: 'Ελληνικά',         dir: 'ltr' },
  { code: 'th', apiCode: 'th',    name: 'Thai',        native: 'ไทย',              dir: 'ltr' },
  { code: 'vi', apiCode: 'vi',    name: 'Vietnamese',  native: 'Tiếng Việt',       dir: 'ltr' },
  { code: 'id', apiCode: 'id',    name: 'Indonesian',  native: 'Bahasa Indonesia', dir: 'ltr' },
  { code: 'uk', apiCode: 'uk',    name: 'Ukrainian',   native: 'Українська',       dir: 'ltr' },
  { code: 'bn', apiCode: 'bn',    name: 'Bengali',     native: 'বাংলা',            dir: 'ltr' },
  { code: 'ms', apiCode: 'ms',    name: 'Malay',       native: 'Bahasa Melayu',    dir: 'ltr' },
  { code: 'ro', apiCode: 'ro',    name: 'Romanian',    native: 'Română',           dir: 'ltr' },
  { code: 'te', apiCode: 'te',    name: 'Telugu',      native: 'తెలుగు',           dir: 'ltr' },
  { code: 'ml', apiCode: 'ml',    name: 'Malayalam',   native: 'മലയാളം',           dir: 'ltr' },
  { code: 'sw', apiCode: 'sw',    name: 'Swahili',     native: 'Kiswahili',        dir: 'ltr' },
  { code: 'af', apiCode: 'af',    name: 'Afrikaans',   native: 'Afrikaans',        dir: 'ltr' },
];
